### ISSUE TITLE
RSVP to workshop by commenting on this issue!

### ISSUE THREAD

**Issue by jjfiv** [CSWomenUMass/git#9]
The workshop will be on Tuesday from 4-6p in CS150/151.

**Comment by etosch** [comment]
I'm going! :+1:

**Comment by Shamya** [comment]
I'm going :P

**Comment by cibelemf** [comment]
I will be there after the Theory seminar :)

**Comment by strubell** [comment]
I will be there!

**Comment by mhjang** [comment]
Yes I am going too! :+1:

**Comment by sherinaseri** [comment]
I am going

**Comment by weize** [comment]
I'm in

**Comment by yamintun** [comment]
I am going

**Comment by belindanju** [comment]
I will be there as well!  Just to make sure, the workshop is on **Oct 27**, correct?

**Comment by Shamya** [comment]
yes. Tuesday, Oct 27.

**Comment by lynn99** [comment]
I will get there about 4:30 if that's OK.

**Comment by etosch** [comment]
@lynn99 : yup, that's fine.

**Comment by lynn99** [comment]
A number of us in our group have been encouraged to attend this workshop. 

However, I think some of us do not know enough command line syntax to follow the instructions on Bootcamp.

I was able to install Brew, but don’t know how to download and fork repositories or to work from command line other than by pasting commands. And then don’t understand what I get back.

Is this anything like Sourcetree? I see forks there but have never created one.

Is this workshop suitable for those of us who do not know how to work from the command line?  Thanks!

—Lynn

---

Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by tao2020** [comment]
i am going!

**Comment by etosch** [comment]
@lynn

> A number of us in our group have been encouraged to attend this workshop.
> Awesome!
> 
> However, I think some of us do not know enough command line syntax to 
> follow the instructions on Bootcamp.
> 
> I was able to install Brew, but don’t know how to download and fork 
> repositories or to work from command line other than by pasting 
> commands. And then don’t understand what I get back.
> Okay, so where are you getting stuck? If you have brew, you should be 
> able to install git like so:

`brew install git`

brew usually gives back decent errors. If you are getting weird stuff 
back or don't understand them, can you create an issue on the bootcamp 
repository? This has to be done using the web interface.

Once you have git, you should be good to go for the git workshop.

The rest of the stuff in bootcamp is to set up a virtual machine that 
will have all the software you need for the workshops this semester. 
However, if you are on a mac, your command line interface + brew will be 
sufficient for tomorrow.

> Is this anything like Sourcetree? I see forks there but have never 
> created one.
> I'm not sure what sourcetree is, but you cannot fork from the command 
> line. Forking is a GitHub thing, not a git thing. Therefore, you have to 
> do it using the web interface.
> 
> Is this workshop suitable for those of us who do not know how to work 
> from the command line? Thanks!
> Yes! Our next session is UNIX basics (basically, a compressed version of 
> the undergraduate course), but we are running git first, so that we can 
> more easily share materials.
> 
> —Lynn
> 
> ---
> 
> Lynn Stephens
> Post Doctoral Researcher
> School of Computer Science and
> College of Education
> University of Massachusetts—Amherst
> (413) 230-4634
> 
> On Oct 26, 2015, at 10:20 AM, etosch notifications@github.com wrote:
> 
> > @lynn99 : yup, that's fine.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSWomenUMass/git/issues/9#issuecomment-151158691.

## 

Emma Tosch
PhD Candidate, College of Information & Computer Sciences
University of Massachusetts Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by lynn99** [comment]
Great!

I will paste 'brew install git’ at the command line and see what happens.

—Lynn

**Comment by etosch** [comment]
fwiw, you should get in the habit of typing these commands -- it may 
take longer, but it helps internalize the right commands to use.

On 10/26/15 10:51 AM, lynn99 wrote:

> Great!
> 
> I will paste 'brew install git’ at the command line and see what happens.
> 
> —Lynn
> 
> On Oct 26, 2015, at 10:48 AM, etosch notifications@github.com wrote:
> 
> > @lynn
> > 
> > On 10/26/15 10:37 AM, lynn99 wrote:
> > 
> > > A number of us in our group have been encouraged to attend this 
> > > workshop.
> > > Awesome!
> > > 
> > > However, I think some of us do not know enough command line syntax to
> > > follow the instructions on Bootcamp.
> > > 
> > > I was able to install Brew, but don’t know how to download and fork
> > > repositories or to work from command line other than by pasting
> > > commands. And then don’t understand what I get back.
> > > Okay, so where are you getting stuck? If you have brew, you should be
> > > able to install git like so:
> > 
> > `brew install git`
> > 
> > brew usually gives back decent errors. If you are getting weird stuff
> > back or don't understand them, can you create an issue on the bootcamp
> > repository? This has to be done using the web interface.
> > 
> > Once you have git, you should be good to go for the git workshop.
> > 
> > The rest of the stuff in bootcamp is to set up a virtual machine that
> > will have all the software you need for the workshops this semester.
> > However, if you are on a mac, your command line interface + brew 
> > will be
> > sufficient for tomorrow.
> > 
> > > Is this anything like Sourcetree? I see forks there but have never
> > > created one.
> > > I'm not sure what sourcetree is, but you cannot fork from the command
> > > line. Forking is a GitHub thing, not a git thing. Therefore, you 
> > > have to
> > > do it using the web interface.
> > > 
> > > Is this workshop suitable for those of us who do not know how to work
> > > from the command line? Thanks!
> > > Yes! Our next session is UNIX basics (basically, a compressed 
> > > version of
> > > the undergraduate course), but we are running git first, so that we can
> > > more easily share materials.
> > > 
> > > —Lynn
> > > 
> > > ---
> > > 
> > > Lynn Stephens
> > > Post Doctoral Researcher
> > > School of Computer Science and
> > > College of Education
> > > University of Massachusetts—Amherst
> > > (413) 230-4634
> > > 
> > > On Oct 26, 2015, at 10:20 AM, etosch notifications@github.com wrote:
> > > 
> > > > @lynn99 : yup, that's fine.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/CSWomenUMass/git/issues/9#issuecomment-151158691.
> > 
> > ## 
> > 
> > Emma Tosch
> > PhD Candidate, College of Information & Computer Sciences
> > University of Massachusetts Amherst
> > etosch@cs.umass.edu
> > http://cs.umass.edu/~etosch
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSWomenUMass/git/issues/9#issuecomment-151163099.

## 

Emma Tosch
PhD Candidate, College of Information & Computer Sciences
University of Massachusetts Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by Sandhya0204** [comment]
I'm going!

**Comment by minghuitai** [comment]
I am going!

**Comment by sdon16** [comment]
I am going!

**Comment by AnupamaP** [comment]
I'm in!

**Comment by dallessio** [comment]
I will be there.

**Comment by sandysa** [comment]
I will be there

**Comment by poochi** [comment]
I will be there

**Comment by saulshanabrook** [comment]
I'll be there!

**Comment by kepingbi** [comment]
I am going!

**Comment by aarshpatel** [comment]
I will be there!

**Comment by lohith444** [comment]
I am going!

**Comment by RoseTharailJohn** [comment]
definitely going :+1:

**Comment by etosch** [comment]
Thanks, everyone! We'll be getting refreshments for 24 people.

**Comment by strubell** [comment]
🍩👍

**Comment by akobre01** [comment]
I will be there (but probably a little late)!

**Comment by Shamya** [comment]
Hi all,

If you are participating in today's workshop, kindly fill in this survey
_BEFORE THE WORKSHOP_-

https://docs.google.com/forms/d/18SY4k5zZut2HwziR3bw6nuY1itaXe69CATN3W04XrAg/viewform?c=0&w=1

regards,

CS Women

-Shamya

**Comment by Shamya** [comment]
Materials from today's workshop -
[Cheatsheet.pdf](https://github.com/CSWomenUMass/git/files/22069/Cheatsheet.pdf)
[GITPreso.pdf](https://github.com/CSWomenUMass/git/files/22071/GITPreso.pdf)
